### ISSUE TITLE
Unable to import using Gradle

### ISSUE THREAD

**Issue by arindammitra06** [AmniX/HighPassSkinSmoothing-Android#2]
Hi I am new in Android. I want to use your library but is unable to do so because you did not share the Gradle import script. Can you please share how to import its in using gradle like compile '?'... The library looks promising.

**Comment by AmniX** [comment]
Write now, this Library is not available through Gradle Dependency. You need to download or clone this and import this library as a module, Don't forget to setup you NDK environment first.' 

Happy Coding 👍
